In [1]:
#imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('train.csv')

In [3]:
dig = df.isnull()

In [4]:
df[df.apply(lambda x: x.count(), axis = 1) < 785]

Empty DataFrame
Columns: [label, pixel0, pixel1, pixel2, pixel3, pixel4, pixel5, pixel6, pixel7, pixel8, pixel9, pixel10, pixel11, pixel12, pixel13, pixel14, pixel15, pixel16, pixel17, pixel18, pixel19, pixel20, pixel21, pixel22, pixel23, pixel24, pixel25, pixel26, pixel27, pixel28, pixel29, pixel30, pixel31, pixel32, pixel33, pixel34, pixel35, pixel36, pixel37, pixel38, pixel39, pixel40, pixel41, pixel42, pixel43, pixel44, pixel45, pixel46, pixel47, pixel48, pixel49, pixel50, pixel51, pixel52, pixel53, pixel54, pixel55, pixel56, pixel57, pixel58, pixel59, pixel60, pixel61, pixel62, pixel63, pixel64, pixel65, pixel66, pixel67, pixel68, pixel69, pixel70, pixel71, pixel72, pixel73, pixel74, pixel75, pixel76, pixel77, pixel78, pixel79, pixel80, pixel81, pixel82, pixel83, pixel84, pixel85, pixel86, pixel87, pixel88, pixel89, pixel90, pixel91, pixel92, pixel93, pixel94, pixel95, pixel96, pixel97, pixel98, ...]
Index: []

[0 rows x 785 columns]

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [6]:
data = df.head(20000)

In [7]:
Y = data['label']
X = data.drop('label', axis = 1)
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.3,random_state = 101)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [9]:
classifier = RandomForestClassifier(n_estimators  = 50, criterion = 'entropy', random_state=0)

In [10]:
classifier.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=50,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [11]:
Y_pred_train = classifier.predict(X_train)
Y_pred_test = classifier.predict(X_test)

In [12]:
#print(confusion_matrix(Y_train,Y_pred_train))
print(classification_report(Y_train,Y_pred_train))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1365
           1       1.00      1.00      1.00      1566
           2       1.00      1.00      1.00      1408
           3       1.00      1.00      1.00      1447
           4       1.00      1.00      1.00      1378
           5       1.00      1.00      1.00      1272
           6       1.00      1.00      1.00      1404
           7       1.00      1.00      1.00      1440
           8       1.00      1.00      1.00      1342
           9       1.00      1.00      1.00      1378

    accuracy                           1.00     14000
   macro avg       1.00      1.00      1.00     14000
weighted avg       1.00      1.00      1.00     14000



In [58]:
print(confusion_matrix(Y_test, Y_pred_test))
print(classification_report(Y_test,Y_pred_test))

[[558   0   0   0   1   0   3   0   5   0]
 [  0 678   3   5   0   5   2   2   4   1]
 [  6   1 557   2   7   0   6   7  15   1]
 [  2   0  12 567   1  22   3   2  17   7]
 [  1   1   0   1 561   1   7   1   4  16]
 [  3   0   1   9   0 498   6   0   4   1]
 [  4   0   1   0   1   7 563   0   2   0]
 [  3   3  15   2   8   0   0 578   6  15]
 [  5   1   3   9   5   5   3   2 535   5]
 [  3   0   4  10  17   7   0   3   4 554]]
              precision    recall  f1-score   support

           0       0.95      0.98      0.97       567
           1       0.99      0.97      0.98       700
           2       0.93      0.93      0.93       602
           3       0.94      0.90      0.92       633
           4       0.93      0.95      0.94       593
           5       0.91      0.95      0.93       522
           6       0.95      0.97      0.96       578
           7       0.97      0.92      0.94       630
           8       0.90      0.93      0.92       573
           9       0.92     

In [61]:
testing = pd.read_csv('test.csv')

MemoryError: 

In [ ]:
testing[testing.apply(lambda x: x.count(), axis =1 ) < 784]

In [33]:
fpredictions = classifier.predict(testing)

In [34]:
testing['Label'] = fpredictions

In [35]:
l = []
for i in range(1,28001):
    l.append(i)
l = np.array(l)

In [36]:
testing['ImageId'] = l

In [41]:
testing[['ImageId', 'Label']].to_csv('Digit_solution.csv')

MemoryError: 